.\" dummy line
.TH MRED 1 "8 June 1996"
.UC 4
.SH NAME
mred \- The Rice PLT GUI engine
.SH SYNOPSIS
.B mred
[-s
.I sysfile
]
[-q | --no-init-file]
[-nu ]
[-f
.I file
]
[-e
.I expr
]
[--
.I arguments
]
[
.I file
]
.SH DESCRIPTION
.I MrEd
is Rice University's Programming Languages Group's GUI
execution engine.
.I MrEd
runs on a variety of platforms.
.PP
The -s flag directs
.I MrEd
to load the startup system from
a particular file. This overrides the system directory
search path described below in FILES and must come before all other
arguments.
.PP
The -q or --no-init-file flag prevents 
.I MrEd
from loading
the user's startup file ".mredrc" in the user's home
directory.
.PP
multiple -f
and -e flags can be specified. For each -e flag, the corresponding
expression is evaluated. For each -f flag, the corresponding file
is loaded (with its directory as the working cirectory).
.PP
If a file appears on the command line with no switches, then it is opened
for editing in 
.I MrEd.
The -- flag means to treat the next argument as a file
to be opened for editing, even if it is "-e" or "-f".
.PP
The -nu flag specifies a non-unit startup. See the Toolbox Manual for more
details on 
.I MrEd's
startup and how to build your own application with 
.I MrEd.
.PP
Once all command line arguments are handled the scheme procedure
mred:startup is called. This procedure is defined by the standard
system, but it can be redefined with the -f or -e flags for
application-specific startup sequences. 
.PP
For further information on
.I MrEd,
please consult the on-line
documentation in the Help menu of the console 
and other information available at
.PP
.ce 1
http://www.cs.rice.edu/CS/PLT/packages/mred/

.SH FILES
If the -s flag is not specified, 
.I MrEd
looks for its standard system file "mrsystem.ss" with the following 
search path:
.IP
* the search path defined by the MREDSYS system evironment 
variable
.IP
* In PLTHOME/mred/system where PLTHOME is replaced with the value of the
PLTHOME environment variable.
.IP
* "/usr/local/lib/plt/mred/system" 
.IP
* "/usr/lib/plt/mred/system"
.IP
* "/usr/local/lib/mred/system"
.IP
* "/usr/lib/mred/system"
.PP

The standard system loads in the core or the mzlib library,
using the following search path:
.IP
* "../mzlib"
.IP
* "../mzscheme/mzlib"
.IP
* "../../mzscheme/mzlib"
.IP
* "PLTHOME/mzscheme/mzlib", where "PLTHOME" is replaced
with the value of the PLTHOME environment variable. 
If the environment variable is undefined, 
"/usr/local/lib/plt/" is used
.PP

.I MrEd
also looks for Xresources in 
.IP
* "~/.mred.resources"
.PP
Xresources in that file override any other resources settings.

.SH BUGS
Email bug reports to plt-bugs@cs.rice.edu.  Please mention
"MrEd" in the subject line or the message.
.SH AUTHOR
.I MrEd
was implemented by Matthew Flatt (mflatt@cs.rice.edu) and Robby Findler
(robby@cs.rice.edu) using wxWindows by Julian Smart et al. and
the conservative garbage collector by Hans Boehm et al.
.SH SEE ALSO
.BR drscheme(1),
.BR mzscheme(1)
